version: "3"
services:
    mymongo:
        image: mongo
        ports:
            - 2717:27017
    mongo-express:
        image: mongo-express
        ports:
            - 8081:8081
        environment:
            - ME_CONFIG_MONGODB_SERVER=mymongo
        depends_on:
            - mymongo
    tor:
        image: dperson/torproxy
        ports:
            - 8118:8118
            - 9050:9050
    my-server:
        build: ./server
        ports:
            - 4000:4000
            - 4545:4545
        environment:
            DB_URL: mongodb://mymongo/intsight-project
        depends_on:
            - mymongo
    my-client:
        build: ./client
        ports:
            - 3000:80
        depends_on:
            - my-server
    scraper:
        build: ./dataFromWeb
        ports:
            - 5000:5000
        depends_on:
            - mymongo
            - tor